version: '3'
networks:
  default:
    external:
      name: compose_container_services_networks

services:

  node_micrososervice:
    build:
      context: ./../../
      dockerfile: ./docker/Dockerfile
    ports:
      - ${WEB_APP_PORT:-4000}:3000
    environment:
      - DB_HOST=node_micrososervice_db
      - DB_PORT=5432
      - LOGZIO_TOKEN=${LOGZIO_TOKEN}
      - JWT_SECRET=${JWT_SECRET}
      - PASSWORD_SALT=${PASSWORD_SALT}
      - JWT_TYPE=${JWT_TYPE}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - API_GATEWAY_ENDPOINT=${API_GATEWAY_ENDPOINT:-http://kong:8001}
    links:
      - node_micrososervice_db
    depends_on:
      - node_micrososervice_db
    command: ["/wait-for-it.sh", "-t", "30", "node_micrososervice_db:5432", "--","npm","--prefix", "/opt/app/", "start"]
    volumes:
      - /private/var/docker/log/node_micrososervice_db:/var/log

  # The postgres database
  node_micrososervice_db:
    restart: always
    image: sameersbn/postgresql:9.6-2
    ports:
      - ${DB_PORT_EXPOSED_ON_HOST:-5435}:5432
    environment:
      - DEBUG=false
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=node_micrososervice_db
      - PG_PASSWORD=postgres
      - DB_TEMPLATE=

      - DB_EXTENSION=

      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=

    volumes:
      - /private/var/docker/postgresql/node_micrososervice_db:/var/lib/postgresql
